#!/bin/bash
USE_OMNISHARP=1

usage()
{
  echo "usage: sgc-tmux [[-o | --no-omnisharp] | [-h | --help]]"
}

while [ "$1" != "" ]; do
    case $1 in
        -o | --no-omnisharp )   shift
                                USE_OMNISHARP=0
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

tmux new -s 'sgc' -d

tmux rename-window ' main'
tmux send-keys "cd ~" C-m

tmux new-window -n ' back'
tmux send-keys "cd ~/sgc/src" C-m
tmux send-keys "nvim" C-m

tmux new-window -n ' front'
tmux send-keys "cd ~/sgc/src/sgc/portal" C-m
tmux send-keys "nvim" C-m

tmux new-window -n ' app-run'
# sec
tmux send-keys "cd ~/sgc/tools" C-m
# cadu
tmux split-window -h 
tmux send-keys "cd ~/sgc/tools" C-m

# cond
tmux select-pane -L 
tmux split-window -v 
tmux send-keys "cd ~/sgc/tools" C-m

# git
tmux select-pane -R 
tmux split-window -v 
tmux send-keys "cd ~/sgc/src" C-m

# serve
tmux split-window -v 
tmux send-keys "sgc-serve" C-m

# omnisharp
tmux select-pane -R 
tmux split-window -v 
if [ "$USE_OMNISHARP" -gt "0" ]; then
  tmux send-keys "sgc-omnisharp" C-m
fi

tmux -2 attach -t sgc
tmux rename-session 'sgc'

